version: '3'

services:
  redis-master1:
    image: redis:5.0
    container_name: redis-master1
    #build: redis-server
    ports:
      - "7000:6379"
      - "17000:16379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.2
    volumes: ["/tmp/config:/config"]
    entrypoint:
         - /bin/bash
         - /config/redis.sh

  redis-master2:
    image: redis:5.0
    container_name: redis-master2
    #build: redis-server
    ports:
      - "7001:6379"
      - "17001:16379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.3
    volumes: ["/tmp/config:/config"]
    entrypoint:
         - /bin/bash
         - /config/redis.sh

  redis-master3:
    image: redis:5.0
    container_name: redis-master3
    # build: redis-server
    ports:
      - "7002:6379"
      - "17002:16379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.4
    volumes: ["/tmp/config:/config"]
    entrypoint:
         - /bin/bash
         - /config/redis.sh

  redis-slave1:
    image: redis:5.0
    container_name: redis-slave1
    # build: redis-server
    ports:
      - "7003:6379"
      - "17003:16379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.5
    volumes: ["/tmp/config:/config"]
    entrypoint:
         - /bin/bash
         - /config/redis.sh

  redis-slave2:
    image: redis:5.0
    container_name: redis-slave2
    # build: redis-server
    ports:
      - "7004:6379"
      - "17004:16379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.6
    volumes: ["/tmp/config:/config"]
    entrypoint:
         - /bin/bash
         - /config/redis.sh

  redis-slave3:
    image: redis:5.0
    container_name: redis-slave3
    # build: redis-server
    ports:
      - "7005:6379"
      - "17005:16379"
    networks:
         extnetwork:
            ipv4_address: 172.19.0.7
    volumes: ["/tmp/config:/config"]
    entrypoint:
         - /bin/bash
         - /config/redis.sh


  # redis-cluster-creator:
  #   container_name: redis-cluster-creator
  #   build: cluster
  #   networks:
  #        extnetwork:
  #   depends_on:
  #     - redis-master1
  #     - redis-master2
  #     - redis-master3
  #     - redis-slave1
  #     - redis-slave2
  #     - redis-slave3
  #   links:
  #     - redis-master1
  #     - redis-master2
  #     - redis-master3
  #     - redis-slave1
  #     - redis-slave2
  #     - redis-slave3

  # redis-sentinel1:
  #   container_name: redis-sentinel1
  #   build: sentinel
  #   networks:
  #        extnetwork:
  #   depends_on:
  #     - redis-master1
  #     - redis-master2
  #     - redis-master3
  #     - redis-slave1
  #     - redis-slave2
  #     - redis-slave3
  # redis-sentinel2:
  #   container_name: redis-sentinel2
  #   build: sentinel
  #   networks:
  #        extnetwork:
  #   depends_on:
  #     - redis-master1
  #     - redis-master2
  #     - redis-master3
  #     - redis-slave1
  #     - redis-slave2
  #     - redis-slave3
  # redis-sentinel3:
  #   container_name: redis-sentinel3
  #   build: sentinel
  #   networks:
  #        extnetwork:
  #   depends_on:
  #     - redis-master1
  #     - redis-master2
  #     - redis-master3
  #     - redis-slave1
  #     - redis-slave2
  #     - redis-slave3

networks:
   extnetwork:
      ipam:
         config:
         - subnet: 172.19.0.0/16
