FROM redis:5.0.3-alpine3.9

MAINTAINER zhangcunxin <cunxinzhang@gmail.com>

EXPOSE 6379 16379

COPY rediscluster.conf /etc/redis/rediscluster.conf
ENTRYPOINT redis-server /etc/redis/rediscluster.conf
